---
- name: Create directories for awslogs install
  file:
    path: "{{ aws_base_awslogs_cache_dir }}"
    state: directory

- name: Get awslogs agent setup official script
  get_url:
    url: "https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py"
    dest: "{{ aws_base_awslogs_cache_dir }}/awslogs-agent-setup.py"
    mode: 0744

- name: Get awslogs agent dependencies
  unarchive:
    remote_src: true
    src: "https://s3.amazonaws.com//aws-cloudwatch/downloads/latest/AgentDependencies.tar.gz"
    dest: "{{ aws_base_awslogs_cache_dir }}"
    creates: "{{ aws_base_awslogs_cache_dir }}/AgentDependencies"

- name: Generate configuration
  template:
    src: awslogs.conf.j2
    dest: "{{ aws_base_awslogs_preconfig_file }}"
  notify: AWSLogs agent setup
